### ISSUE TITLE
Window scale isn't saved to config when using hotkey

### ISSUE THREAD

**Issue by JasonShearer** [snesrev/zelda3#95] opened 2022-09-18 05:57 UTC
Title says it all. It's a minor annoyance, but I think whatever size you set it to during a session should carry over to the next.

**Comment by snesrev** [comment] 2022-09-18 11:21
Nothing gets ever saved to the config file. The config flie is read only...

**Comment by snesrev** [comment] 2022-10-17 22:14
Closing this for now because we're not saving to the config file by design.

**Closed by snesrev** 2022-10-17 22:14 UTC
Labels: wontfix
