### ISSUE TITLE
Changing savestates while in rainy Swamp of Evil causes rain sound effect to persist

### ISSUE THREAD

**Issue by FitzRoyX** [snesrev/zelda3#125] opened 2022-09-27 22:16 UTC
### Describe your bug here. And how to reproduce it.

nm

### What is your build target?

Windows

**Comment by snesrev** [comment] 2022-10-01 00:12
How do I go to rainy misery mire?

**Comment by FitzRoyX** [comment] 2022-10-01 15:26
Call the bird in the light world and go to location 6. Then lift the rock there and enter the warp. Now you're in the Swamp of Evil and it will be raining unless you've beaten the dungeon. Change savestates here.

**Comment by snesrev** [comment] 2022-10-02 00:06
I'm unable to reproduce this. Can you check it has been fixed? Perhaps I fixed it by mistake the other day.

**Comment by Kazuto88** [comment] 2022-10-02 15:32
I just checked this today on the current build - the lingering rain SFX has been fixed, but now it seems the music for the loaded room just fades out upon loading. An easy way to test this: save a state in the church, start a new game, then load the church state. The rain effect will stop, but then the church music will fade to silence.

**Comment by FitzRoyX** [comment] 2022-10-04 19:11
Yeah this is fixed for me in latest master and I can't reproduce Kazuto's issue either.

**Comment by snesrev** [comment] 2022-10-04 21:23
I think this is fixed in the new commit. Please reopen if not.

**Closed by snesrev** 2022-10-04 21:23 UTC
Labels: bug
